### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by loopy321** [Fitbit/sdk-ifttt-demo#1]
Hello,

I tried following the "demon_trigger" event and the Versa app says "No Hooks!" even after syncing.

Any ideas for how to get this working?

**Comment by orviwan** [comment]
Did you enter the correct trigger name? `demo_trigger` and enter your API key in the settings page?

![cap](https://user-images.githubusercontent.com/876597/55760656-97d87500-5a11-11e9-804c-b874f7cd163a.png)

**Comment by loopy321** [comment]
Yes, I setup an IFTTT trigger just like above.  I even tried using a "custom webhooks" of 
testhook:https://maker.ifttt.com/trigger/testhook/with/key/{KEY}

but same result of "No hook!  use the mobile app to add some hooks"

Maybe the problem is related to the hooks setting page having a "Sync setting to device" that does not appear to do anything when pressed.  However, I did sync the Versa with the app after adding the hook.

Thanks,
Bob

**Comment by orviwan** [comment]
I have tested this in the simulator and on a real device and this works as intended.
